### ISSUE TITLE
Protocol & Architecture Specifications

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#355]
**Description**

Complete FPC protocol and high-level overall architecture specification for MVP / RFC
- [x] Determine what diagrams are necessary (see also issue #356)
- [ ] Finish registration flow (see, e.g., issue #303 and PR #333)
- [x] Finish lifecycle flow (PR #353 & PR #374 )
- [x] cleanup/validate key-dist flows (see, e.g., issue #303 and PR #375 & #379)
- [x] cleanup/validate execution flows (see, e.g., issue #303 & #361 and PR #377 & #378)

Protocol must cover everything from [MVP milestone](https://github.com/hyperledger-labs/fabric-private-chaincode/milestone/38) but should also cover what we already have discussed as limitations and way to go forward at least as comments so prior discussions/insights is not lost)

See for more long-term work-items [Protocol & Architecture Specifications Milestone](https://github.com/hyperledger-labs/fabric-private-chaincode/milestone/9)

**Comment by mbrandenburger** [comment]
Regarding the step `Determine what diagrams are necessary`

Jeb's recent update on the RFC added diagrams to the RFC.

In contains a component diagram and a series of diagrams to the describe the transaction flow. I think we should keep the component diagram and reduce the number of flow diagrams where we can.

See https://github.com/mbrandenburger/fabric-rfcs/blob/31e9afa647271dd31fdc216c4a9340fb37759629/text/0000-fabric-private-chaincode.md

Additionally, we should add a simplified version of the creation/registration and how FPC chaincode interacts with the Ledger enclave to validate input (similar to Figure 4 in the paper https://arxiv.org/pdf/1805.08541.pdf).

WDYT? @bvavala @g2flyer @jrlinton

**Comment by g2flyer** [comment]
I think there are two separate questions:
1. what do we need for the high-level description for the RFC
1. what do we need for the detail design/protocol (i.e. UML diagrams)

For 2. i guess it is essentially what we already have 
- fpc-lifecycle-v2.puml
- fpc-registration.puml
- fpc-key-dist.puml
- fpc-cc-invocation.puml
- fpc-cc-execution.puml   
- fpc-validation.puml
- fpc-components.puml
(and potentially fpc-integration-touchpoints.puml as overview, maybe with cross references to the other diagrams?)

For 1., afaict, the anoted diagrams are exactly the ones we used in some talks. Given that we had some reason to highlight these steps then, it seems like a reasonable approach just to inline them the way Jeb has done. I have no strong opinion. I certainly do not see a real problem having all of them, in particular given that we do have them already and don't have to generate them first.

That said, we definitely should make sure that we also keep the source of the png version controlled and not only the png so we can easily apply any changes later (e.g., if we want to reconcile naming conventions with what we discussed this morning ...)

**Comment by bvavala** [comment]
I think 
* the diagrams add clarity, particularly for first-time readers;
* also we should not inline the UML diagrams, and rather provide them on request (or at most have a reference to them)
* also, and most importantly, we need more input

**Comment by g2flyer** [comment]
> * the diagrams add clarity, particularly for first-time readers;
> * also we should not inline the UML diagrams, and rather provide them on request (or at most have a reference to them)
> * also, and most importantly, we need more input

Just to make sure: with "more input" i guess you mean external input from RFC reviewers/fabric maintainers? If so i definitely agree (as i do with your first two points which seem consistent with my comments above?)
