### ISSUE TITLE
FPC RFC

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#356]
**Is your feature request related to a problem? Please describe.**
FPC RFC Completed/Accepted by Fabric.

Work-in-progress exists in https://github.com/hyperledger/fabric-rfcs/pull/21 but needs revisions and probably also input from issue #355.

- [x] 1. clean-up with focus motivation (value proposition) & scope (which things are not supported) based on current comments
  - [x] collect work-items (marcus/jeb already having made some?!)
  - [x] close work-items identified above ...
  - [x] Add High-level diagram making clear role of TEE & that everything is encrypted/protected outside of TEE
  - [ ] ~fpc + fabric development models~ (should be covered below)
- [x] 2. document(external) functional view details as of Tech Preview (depends on issue #358)
  - [x] additional cli mgmt commands 
    - [x] content (see PR #376 / `docs/design/fabric-v2+/fpc-management.md`)
    - [x] integration in RFC (i.e., reference above doc)
  - [x] FPC CC/shim API 
    - [x] content (see `ecc_enclave/enclave/shim.h`)
    - [x] integration in RFC (i.e., just reference above or "markdown" above for easier consumptipon) 
  - [x] client-side cc execution API (client sdk, cli initially, nothing changed, should be transparent?) 
  - [x] [maybe] development environment given that only (HW) sgx support for linux (-> seamless docker for mac (& windows?), see issue #348)
  - [x] Roadmap of features
- [x] 3. Technical/architectural description
  - [x] add High-level diagrams on architecture 
  - [x]  UML diagrams (either include as appendix or just just as references to files in repo and how to build)  (depends on issue #355)
  - [x] maybe short paragraph on Fabric integration/changes?

**Comment by g2flyer** [comment]
Given the potentially too big scope of the current single RFC, we might consider splitting it up in separate RFCs. Potential break-down lines could be.
- value proposition
- external interfaces / programming model
- architecture & protocols
- fabric integration changes
- fpc + fabric development models
The hope would be that this might help in making better progress and also might align better with the split between Tech Preview and MVP?

**Comment by mbrandenburger** [comment]
Here my list of TODOs for the RFC ...

- [ ] Add more figures to clarify proposal
- [ ] Stress that fact FPC requires code identity (MRENCLAVE); (we don't support multiple implementations for a single chaincode paradigm)
- [ ] Describe how to handle peer restarts
- [ ] Add key distribution protocol section
- [ ] More details on testing; make sure you can develop FPC code on mac

**Comment by mbrandenburger** [comment]
Final review requested https://github.com/mbrandenburger/fabric-rfcs/pull/11
Once this is merged, this issue can be closed,

**Comment by mbrandenburger** [comment]
Merged new revision into the RFC branch. https://github.com/mbrandenburger/fabric-rfcs/pull/11
