### ISSUE TITLE
Global Makefile

### ISSUE THREAD

**Issue by g2flyer** [hyperledger-labs/fabric-private-chaincode#38]
- [x] build system with a top-level make and a make file in each module. More details in #56 
  - build
  - test
  - check
  - integration (end-to-end-test (just calling run-auction initially?))
  - clean

- [x] config.mk file with global variables like
  - GO
  - GOFLAGS

- [x] code checking target. More details in #55 

- [x] refactoring of ecc (SDKization)
  - renaming of component names from trusted to secure, e.g.,  tlcc -> slcc
  - ecc only includes SDK (with a library)
  - auction goes to examples/auction
    - fabric/sgxconfig might also move to examples?
      - we could also replace all /path/to/fabric by $(FABRIC_SRC_ROOT)/.. with FABRIC_SRC_ROOT as $(SCC_ROOT)/../../hyperledger/fabric/ (ie., assume a single root in GOPATH and then all paths to fabric can be done in relative paths ..
    => delegated to issue #69 

- [x] Nanopb refactoring. More details in #55 

- [x] update READMEs to match above changes ..
